#!/usr/bin/env bash
set -exu

check_installer() {
  if [ -e /etc/NIXOS ]; then
    echo -e "Running in the NixOS installer environment."
  else
    echo -e "Not running in the NixOS installer environment."
    exit 1
  fi
}

cleanup() {
  rm -rf wabisabi-main.zip wabisabi-main wabisabi
}

download_config() {
  curl -LJ0 https://github.com/na-son/wabisabi/archive/main.zip -o wabisabi-main.zip
  unzip wabisabi-main.zip
  cd wabisabi-main
}

run_disko() {
  sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes \
    github:nix-community/disko -- --mode zap_create_mount ./modules/nixos/disk-config.nix
}

setup_files() {
  sudo mkdir -p /mnt/etc/nixos
  sudo cp -r * /mnt/etc/nixos
  cd /mnt/etc/nixos
}

install_nixos() {
  echo "Disk initialization complete. ________________________________________"
  echo "Installing NixOS........................................"

  read -p "Target: " target
  sudo nixos-install --flake .#$target $@
  sudo chmod -R 775 /mnt/etc/nixos
}

#prompt_reboot() {
#  read -p "Do you want to reboot now? (yes/no) " choice
#  case "$choice" in
#  y|Y|yes|YES ) echo -e "Rebooting..." && sudo reboot;;
#  * ) echo -e "Reboot skipped.";;
#  esac
#}

cleanup
check_installer
download_config
run_disko
setup_files
install_nixos
#prompt_reboot
